# yamllint disable rule:document-start rule:line-length

# ##############################################################################
# ACTION
# ##############################################################################

# ------------------------------------------------------------------------------
# METADATA
# ------------------------------------------------------------------------------

#
# GENERAL
#

name: "Prepare"
description: "Prepare the runner environment for jobs of a specific project type"

#
# BRANDING
#

branding:
  icon: "circle"
  color: "gray-dark"

# ##############################################################################
# INPUTS
# ##############################################################################

inputs:
  job:
    description: "Job we are preparing for"
    required: true

  type:
    description: "Project type we are preparing for"
    required: true

  version_alejandra:
    description: "Version of alejandra to be installed"
    required: false
    default: "4.0.0"

  version_checkov:
    description: "Version of checkov to be installed"
    required: false
    default: "3.2.501"

  version_direnv:
    description: "Version of direnv to be installed"
    required: false
    default: "2.37.1"

  version_hadolint:
    description: "Version of hadolint to be installed"
    required: false
    default: "2.14.0"

  version_task:
    description: "Version of task to be installed"
    required: false
    default: "3.50.0"

  version_tenv:
    description: "Version of tenv to be installed"
    required: false
    default: "4.9.3"

  version_tflint:
    description: "Version of tflint to be installed"
    required: false
    default: "0.61.0"

# ##############################################################################
# OUTPUTS
# ##############################################################################

#
# Empty
#

# ##############################################################################
# RUN
# ##############################################################################

runs:
  using: "composite"
  steps:
    - name: check runner os
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "::error title=unsupported os"
        exit 1

    - name: setup task
      shell: bash
      run: |
        if [ ${{ runner.arch }} = "ARM64" ]; then
          cpuarch="arm64"
        elif [ ${{ runner.arch }} = "X64" ]; then
          cpuarch="amd64"
        else
          echo "::error title=unsupported cpu architecture"
          exit 1
        fi

        curl -sOL "https://github.com/go-task/task/releases/download/v${{ inputs.version_task }}/task_checksums.txt"
        curl -sOL "https://github.com/go-task/task/releases/download/v${{ inputs.version_task }}/task_linux_${cpuarch}.tar.gz"
        sha256sum -c task_checksums.txt --ignore-missing
        tar zxf task_linux_${cpuarch}.tar.gz task
        mv task /usr/local/bin/
        chmod +x /usr/local/bin/task
        rm -f task_*

    - name: setup direnv
      shell: bash
      run: |
        if [ ${{ runner.arch }} = "ARM64" ]; then
          cpuarch="arm64"
          checksum="2a9cef8d73521d6a3ec3f2871c4b747b8c4cc038628c1b57a7efa42b393a2d82"
        elif [ ${{ runner.arch }} = "X64" ]; then
          cpuarch="amd64"
          checksum="1f1b93dd6f38523fde26dfac96151ef9d31a374e3005cd3345fb93555ae0c9b5"
        else
          echo "::error title=unsupported cpu architecture"
          exit 1
        fi

        curl -sOL "https://github.com/direnv/direnv/releases/download/v${{ inputs.version_direnv }}/direnv.linux-${cpuarch}"
        echo "${checksum}  direnv.linux-${cpuarch}" | sha256sum -c -
        mv "direnv.linux-${cpuarch}" /usr/local/bin/direnv

    - name: setup hadolint
      if: ${{ inputs.type == 'container' && inputs.job == 'lint' }}
      shell: bash
      run: |
        if [ ${{ runner.arch }} = "ARM64" ]; then
          cpuarch="arm64"
        elif [ ${{ runner.arch }} = "X64" ]; then
          cpuarch="x86_64"
        else
          echo "::error title=unsupported cpu architecture"
          exit 1
        fi

        curl -sOL "https://github.com/hadolint/hadolint/releases/download/v${{ inputs.version_hadolint }}/hadolint-linux-${cpuarch}"
        curl -sOL "https://github.com/hadolint/hadolint/releases/download/v${{ inputs.version_hadolint }}/hadolint-linux-${cpuarch}.sha256"
        sha256sum -c "hadolint-linux-${cpuarch}.sha256"
        mv "hadolint-linux-${cpuarch}" /usr/local/bin/hadolint
        chmod +x /usr/local/bin/hadolint
        rm -f hadolint-*

    - name: install checkov
      if: ${{ (inputs.type == 'container' || inputs.type == 'terraform') && inputs.job == 'scan' }}
      shell: bash
      run: |
        pip install --user checkov==${{ inputs.version_checkov }}
        which checkov

    - name: setup qemu
      if: ${{ inputs.type == 'container' && (inputs.job == 'ci' || inputs.job == 'cd') }}
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

    - name: setup docker buildx
      if: ${{ inputs.type == 'container' && inputs.job == 'cd' }}
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

    - name: setup cosign
      if: ${{ inputs.type == 'terraform' }}
      uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.0

    - name: setup tenv
      if: ${{ inputs.type == 'terraform' }}
      shell: bash
      run: |
        if [ ${{ runner.arch }} = "ARM64" ]; then
          cpuarch="arm64"
        elif [ ${{ runner.arch }} = "X64" ]; then
          cpuarch="amd64"
        else
          echo "::error title=unsupported cpu architecture"
          exit 1
        fi

        curl -sOL "https://github.com/tofuutils/tenv/releases/download/v${{ inputs.version_tenv }}/tenv_v${{ inputs.version_tenv }}_${cpuarch}.deb"
        curl -sOL "https://github.com/tofuutils/tenv/releases/download/v${{ inputs.version_tenv }}/tenv_v${{ inputs.version_tenv }}_${cpuarch}.deb.pem"
        curl -sOL "https://github.com/tofuutils/tenv/releases/download/v${{ inputs.version_tenv }}/tenv_v${{ inputs.version_tenv }}_${cpuarch}.deb.sig"
        curl -sOL "https://github.com/tofuutils/tenv/releases/download/v${{ inputs.version_tenv }}/tenv_v${{ inputs.version_tenv }}_checksums.txt"
        curl -sOL "https://github.com/tofuutils/tenv/releases/download/v${{ inputs.version_tenv }}/tenv_v${{ inputs.version_tenv }}_checksums.txt.sig"
        curl -sOL "https://github.com/tofuutils/tenv/releases/download/v${{ inputs.version_tenv }}/tenv_v${{ inputs.version_tenv }}_checksums.txt.pem"

        cosign verify-blob \
          --certificate-identity "https://github.com/tofuutils/tenv/.github/workflows/release.yml@refs/tags/v${{ inputs.version_tenv }}" \
          --signature "tenv_v${{ inputs.version_tenv }}_checksums.txt.sig" \
          --certificate "tenv_v${{ inputs.version_tenv }}_checksums.txt.pem" \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          "tenv_v${{ inputs.version_tenv }}_checksums.txt"

        cosign verify-blob \
          --certificate-identity "https://github.com/tofuutils/tenv/.github/workflows/release.yml@refs/tags/v${{ inputs.version_tenv }}" \
          --signature "tenv_v${{ inputs.version_tenv }}_${cpuarch}.deb.sig" \
          --certificate "tenv_v${{ inputs.version_tenv }}_${cpuarch}.deb.pem" \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          "tenv_v${{ inputs.version_tenv }}_${cpuarch}.deb"

        sha256sum -c "tenv_v${{ inputs.version_tenv }}_checksums.txt" --ignore-missing
        dpkg -i "tenv_v${{ inputs.version_tenv }}_${cpuarch}.deb"
        rm -f tenv_*

    - name: setup tflint
      if: ${{ inputs.type == 'terraform' }}
      shell: bash
      run: |
        if [ ${{ runner.arch }} = "ARM64" ]; then
          ARCH="arm64"
        elif [ ${{ runner.arch }} = "X64" ]; then
          ARCH="amd64"
        else
          echo "::error title=unsupported cpu architecture"
          exit 1
        fi

        curl -fsSL \
          -o /tmp/tflint.zip \
          "https://github.com/terraform-linters/tflint/releases/download/v${{ inputs.version_tflint }}/tflint_linux_${ARCH}.zip"

        cd /tmp
        unzip tflint.zip
        chmod +x tflint
        mv tflint /usr/local/bin/
        rm -f tflint.zip
        cd -

    - name: setup alejandra
      if: ${{ inputs.type == 'nix' && ( inputs.job == 'ci' || inputs.job == 'lint' ) }}
      shell: bash
      run: |
        if [ ${{ runner.arch }} = "ARM64" ]; then
          ARCH="aarch64"
        elif [ ${{ runner.arch }} = "X64" ]; then
          ARCH="x86_64"
        else
          echo "::error title=unsupported cpu architecture"
          exit 1
        fi

        curl -fsSL \
          -o /usr/local/bin/alejandra \
          "https://github.com/kamadorueda/alejandra/releases/download/${{ inputs.version_alejandra }}/alejandra-${ARCH}-unknown-linux-musl"

        chmod +x /usr/local/bin/alejandra
