name: lint

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: install yamllint
        run: |
          pip install --user yamllint

      - name: lint action.yml
        run: |
          yamllint -c .yamllint.conf action.yml
