name: on tags

on:
  push:
    tags:        
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: lint
        uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: lint
        uses: ./.github/actions/lint
