# ######################################################################################################################
# LICENSE
# ######################################################################################################################

#
# This file is part of container-dev-base.
#
# The container-dev-base is free software: you can redistribute it and/or modify it under the terms of the GNU Affero
# General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# The container-dev-base is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along with container-dev-base. If not, see
# <https://www.gnu.org/licenses/>.
#

# ######################################################################################################################
# WORKFLOW
# ######################################################################################################################

# ----------------------------------------------------------------------------------------------------------------------
# METADATA
# ----------------------------------------------------------------------------------------------------------------------

#
# GENERAL
#

name: Pipeline

#
# TRIGGER
#

on:
  pull_request:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# ######################################################################################################################
# ENVIRONMENT VARIABLES
# ######################################################################################################################

#
# EMPTY
#

# ######################################################################################################################
# JOBS
# ######################################################################################################################

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Yamllint
        run: |
          pip install --user yamllint
          which yamllint

      - name: Lint "action.yml"
        run: |
          yamllint action.yml

      - name: Test Lint of Container Projects
        uses: ./
        with:
          type: container
          job: lint

      - name: Test Scan of Container Projects
        uses: ./
        with:
          type: container
          job: scan

      - name: Test CI of Container Projects
        uses: ./
        with:
          type: container
          job: ci
      
      - name: Test CD of Container Projects
        uses: ./
        with:
          type: container
          job: cd

      - name: Verification
        run: |
          set -e
          which hadolint
          which checkov
          which docker
          docker buildx version
